### ISSUE TITLE
Support for Private Networking

### ISSUE THREAD

**Issue by bigg01** [Azure/kube-egress-gateway#411]
# Questions

Hello 
Nice piece of work.
From the documentation, I'm not **100% sure if you** support private networks end-to-end.
We need to reach some endpoints through Site2Site VPN in the datacenter, but things like LBs want to reach the endpoints in the datacenter from an Azure-centric IP address, which should not have access to the endpoint.

 **“for Load Balancer you must allow 168.63.129.16 IP address in any Network.”**

**Comment by jwtty** [comment]
Close the issue as we don't see any more updates. Feel free to reopen if you still have any questions.
