### ISSUE TITLE
Managed identity invalid request identity not found

### ISSUE THREAD

**Issue by wizedkyle** [Azure/kube-egress-gateway#644]
Hey all, 

I have been working through implementing this on AKS (1.28.5) and am wanting to use a Managed Identity for authentication however, when I deploy a Static Gateway Configuration the controller returns "invalid_request" identity not found.

<img width="706" alt="image" src="https://github.com/user-attachments/assets/0cf30d95-5cc2-4833-95ef-4c569e93600d">

I have double checked my configuration and it appears to be correct based on the documentation provided for context here is the helm install command including the variables (some redacted for obvious reasons):

```
      - name: Install Kube Egress Gateway
        run: |
          helm upgrade --install kube-egress-gateway ./kube-egress/helm/kube-egress-gateway \
            --namespace kube-egress-gateway-system \
            --create-namespace \
            --set common.imageRepository=mcr.microsoft.com/aks \
            --set common.imageTag=v0.0.11 \
            --set config.azureCloudConfig.cloud="AzurePublicCloud" \
            --set config.azureCloudConfig.tenantId="${{ secrets.AZURE_TENANT_ID }}" \
            --set config.azureCloudConfig.subscriptionId="${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            --set config.azureCloudConfig.useManagedIdentityExtension=true \
            --set config.azureCloudConfig.userAssignedIdentityID="${{ env.EGRESS_GATEWAY_CLIENT_ID }}" \
            --set config.azureCloudConfig.resourceGroup="${{ env.RG_NAME }}" \
            --set config.azureCloudConfig.userAgent="kube-egress-gateway-controller" \
            --set config.azureCloudConfig.location="${{ vars.LOCATION }}" \
            --set config.azureCloudConfig.gatewayLoadBalancerName="kubeegressgateway" \
            --set config.azureCloudConfig.vnetName="${{ env.VNET_NAME }}" \
            --set config.azureCloudConfig.subnetName="${{ env.SUBNET_NAME }}"
```

I have checked the `kube-egress-gateway-azure-cloud-config` secret that is created and it has all the correct information supplied. 

From my understanding of Pod level authentication to Azure services using managed identities you need to use [Azure Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet) which I have used for custom built applications running in pods on AKS. This requires the use of labels on the pod such as "azure.workload.identity/use: "true"" and a relevant ServiceAccount with the "azure.workload.identity/client-id" annotation to allow this to work. Based on the error provided and the fact the URL being requested is `http://169.254.169.254/metadata/identity/oauth2/token` which is typically used for VM Instance Metadata Service (IMDS) I'm not sure if managed identity auth is configured properly at the pod level nor did I think pods had access to IMDS hence the need for workload identities. 

I am going to try client ID/client secret auth which I assume will work (will report back) but I am not sure if there is something subtle I have missed or if there is an underlying issue.

**Comment by wizedkyle** [comment]
Just adding an update, I switched to using app registration client/secret initially this also provided the same error but noticed when deploying through helm it was setting the `userAssignedIdentityID` to a placeholder GUID which the controller wouldn't accept stating `useManagedIdentityExtension` needed to be set to true.

Work around was to modify the secret and remove the value, though there may be a fix through Helm to prevent it from setting these values or specify the exact values file.

**Comment by jwtty** [comment]
Thanks for the issue. For your app registration client/secret, I'll fix the helm chart.

**Comment by jwtty** [comment]
For the msi issue, what msi client ID did you put in `env.EGRESS_GATEWAY_CLIENT_ID`?

**Comment by wizedkyle** [comment]
@jwtty For the MSI client ID I put the Client ID of the User Assigned Managed Identity in Azure.

**Comment by jwtty** [comment]
You need to attach the msi to the vmss where your kube-egress-gateway-controller is running.

**Comment by wizedkyle** [comment]
@jwtty From my understanding there is no way to assign a user managed identity to specific AKS node pool. Based on the comment in #645 specifically the comment:

> Hi @wizedkyle, did you create the vmss BEFORE running the controller? You have to manually create the vmss as the gateway. I checked Azure log and it shows the vmss was not created before kube-egress-gateway-controller tried to update it.
> 
> BTW, aks integration with this feature is close to public preview. With aks integration, we are going to provision the vmss as an agentpool.

Does that mean using an AKS provisioned node pool at the moment isn't supported?
